let produtoJson = [
  {
    id: 1,
    name: "Guarda-Chuva",
    img: "/img/produtos/p001.png",
    price: 18.9,
    //sizes: ["320g", "530g", "860g"],
    description: "Descrição opcional",
  },
  {
    id: 2,
    name: "Lampião De Led Luminária",
    img: "/img/produtos/p002.png",
    price: 69.8,
    description: "Recarregável 8w 36 Leds | Bivolt",
  },
  {
    id: 3,
    name: "Raquete Elétrica Mata Mosquito Dengue Insetos ",
    img: "/img/produtos/p003.png",
    price: 25.9,
    description: "Recarregável | Bivolt",
  },
  {
    id: 4,
    name: "Lanterna Tática 1101",
    img: "/img/produtos/p004.png",
    price: 49.9,
    description: "Recarregável | Light Flashlight Typ",
  },
  {
    id: 1,
    name: "Guarda-Chuva",
    img: "/img/produtos/p001.png",
    price: 18.9,
    //sizes: ["320g", "530g", "860g"],
    description: "Descrição opcional",
  },
  {
    id: 2,
    name: "Lampião De Led Luminária",
    img: "/img/produtos/p002.png",
    price: 69.8,
    description: "Recarregável 8w 36 Leds | Bivolt",
  },
  {
    id: 3,
    name: "Raquete Elétrica Mata Mosquito Dengue Insetos ",
    img: "/img/produtos/p003.png",
    price: 25.9,
    description: "Recarregável | Bivolt",
  },
  {
    id: 4,
    name: "Lanterna Tática 1101",
    img: "/img/produtos/p004.png",
    price: 49.9,
    description: "Recarregável | Light Flashlight Typ",
  },
];
